# Echo client program
import socket


s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()

'''
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
# print('Received ' + repr(data))

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.connect("./_video2img")
s.send('9bZkp7q19f0'.encode('utf-8'))
# data = s.recv(1024)
s.close()
'''